#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-common-sense
Version  : 3.74
Release  : 4
URL      : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.74.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/common-sense-3.74.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-common-sense-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
common::sense - save a tree AND a kitten, use common::sense!
SYNOPSIS
use common::sense;

%package dev
Summary: dev components for the perl-common-sense package.
Group: Development
Provides: perl-common-sense-devel = %{version}-%{release}

%description dev
dev components for the perl-common-sense package.


%package license
Summary: license components for the perl-common-sense package.
Group: Default

%description license
license components for the perl-common-sense package.


%prep
%setup -q -n common-sense-3.74

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-common-sense
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-common-sense/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/common/sense.pm
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/common/sense.pod

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/common::sense.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-common-sense/LICENSE
